### ISSUE TITLE
Explore players from club

### ISSUE THREAD

**Issue by JMMelcrack** [TheNaeem/FifaSharp#1]
At the moment, we are able to explore duplicate items and items in the transfer list, but we aren't able to explore the players that we have on the club.

**Comment by TheNaeem** [comment]
Sorry, just seeing this now! Been busy with college stuff. I'll try to look into this as soon as I can. Thanks.

**Comment by TheNaeem** [comment]
Sorry it took so long, busy times for me. But I just pushed this feature. Check out the ClubSearchQuery class and read the comments in the class to understand how to use some of the properties. Once you've constructed your query, you can pass it into QueryClubAsync.

Closing this for now, but if you run into any issues with the class feel free to let me know here.

**Comment by JMMelcrack** [comment]
Thanks for the new feature, it will be very helpful for me.
