### ISSUE TITLE
Search for a player by name

### ISSUE THREAD

**Issue by sdfartem** [TheNaeem/FifaSharp#2]
Hello, I wanted to clarify whether it is possible to search for a player in the transfer market by name, I just did not notice this feature and if it is still not implemented, for what reasons, I would like to know what difficulties there were with this, I am just writing my application using your library and this functionality would help a lot)

**Comment by TheNaeem** [comment]
To search for a specific player on the transfer market you need to query by their ID.

You can use this endpoint to match player name to ID: https://eafc25.content.easports.com/fc/fltOnlineAssets/25E4CDAE-799B-45BE-B257-667FDCDE8044/2025/fut/items/web/players.json

**Comment by sdfartem** [comment]
thank you very much)

**Comment by sdfartem** [comment]
I also wanted to clarify, is this database updated with the release of new maps? And are there any other links that may be needed to write my project (I am writing a trade bot)

**Comment by TheNaeem** [comment]
News maps? I assume you mean new players. 

Yeah, this is the endpoint used by the web app, so it updates for any new players or changes.

**Comment by sdfartem** [comment]
And are there any other links that may be needed to write my project? (I am writing a trade bot)

**Comment by sdfartem** [comment]
For example, also about the player's league, club, nationality, rarity
