### ISSUE TITLE
tradeID

### ISSUE THREAD

**Issue by sdfartem** [TheNaeem/FifaSharp#4]
Hi, I wanted to know if you know at what stage the tradeID is generated and if you know the algorithm for generating it, I also wanted to find out directly about
the identifier from PlayerData, this is a unique identification card, which is also static, and do you know if it is possible to make a purchase with it, or by by some other criteria, bypassing the search and going straight to the purchase to increase the speed, I will be grateful for any information) and is it also supported to buy a player without a preliminary search, not using tradeID, but using only his ID? I also wanted to know how you found the endpoints where you send requests in your application, for example, to a transfer store, or to purchase.

**Comment by TheNaeem** [comment]
The trade ID of a card you listed is in the return value of when you call ListItemOnTransferMarketAsync.

You can search for a player on the market by their base player ID, but not by their resource ID. If you want a specific version of the card you will need to search by the correct rarity.

If you just read the code in FutClient.cs a lot of your questions would be answered...

**Comment by sdfartem** [comment]
I also wanted to know how you found the endpoints where you send requests in your application, for example, to a transfer store, or to purchase.

**Comment by TheNaeem** [comment]
Use a web debugger like fiddler
